#!/usr/bin/env python3
"""
conservation_null_test.py

Degree-preserving randomisation test for the conserved co-expression core.

PURPOSE
-------
The manuscript reports 118 orthogroups whose co-expressolog pairs are present in
*every* pairwise species comparison (116 forming fully interconnected cliques),
and interprets these as a regulatory core conserved across >300 My. A reviewer
will ask whether that number exceeds what is expected by chance given the size
and topology of the networks. This script answers that by comparing the observed
count against a null generated by degree-preserving edge rewiring.

Why degree-preserving: high-degree (hub) genes share neighbours by chance, so a
naive permutation inflates apparent conservation. Maslov-Sneppen double-edge
swaps scramble *which* genes are connected while holding every gene's degree
(and thus the degree distribution and hub structure) fixed. If the observed
conserved core still exceeds the rewired null, conservation is not a hub artefact.

WHAT IT DOES
------------
1. Loads one co-expression network per species (trimmed edge lists) and the
   orthogroup -> {species: [gene_ids]} mapping.
2. Computes the OBSERVED number of (a) co-expressologs per species pair and
   (b) orthogroups that are co-expressologs in all pairs ("all-pairwise core")
   using a bidirectional hypergeometric neighbourhood-overlap test
   (the ComPlEx logic; Netotea et al. 2014), with BH correction at FDR < 0.1.
3. Builds a NULL: for each replicate, rewires every species network with
   degree-preserving double-edge swaps, recomputes the all-pairwise core size.
4. Reports observed vs null: empirical p-value, fold-enrichment, z-score, and
   writes the null distribution + a histogram.

IMPORTANT
---------
This is a faithful *reimplementation* of the co-expressolog logic so the script
is self-contained. If your published pipeline differs in any detail (mutual-rank
neighbourhood definition, exact FDR handling, clique vs all-pairwise definition),
either (a) set USE_EXTERNAL_CALLER=True and point CALLER_CMD at your own
co-expressolog script so the null reuses your exact method, or (b) tell me the
differences and I will align this implementation. Numbers from this script should
reproduce your observed 118/116 before the null is trusted — verify that first.

INPUT FILES (edit the CONFIG block)
-----------------------------------
networks/<species>.tsv : two columns, gene_a <tab> gene_b  (one undirected edge
                         per line; the trimmed 3%-density network for that species)
orthogroups.tsv        : orthogroup_id <tab> species <tab> gene_id  (long format;
                         one row per gene; species labels must match the network
                         filenames)

Run:  python conservation_null_test.py
Deps: networkx, numpy, scipy, pandas, matplotlib
"""

from __future__ import annotations
import os, glob, itertools, random
from collections import defaultdict
import numpy as np
import pandas as pd
import networkx as nx
from scipy.stats import hypergeom
from statsmodels.stats.multitest import multipletests
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ------------------------------ CONFIG ------------------------------
NETWORK_DIR   = "networks"          # one <species>.tsv edge list per species
ORTHO_FILE    = "orthogroups.tsv"   # long-format orthogroup membership
FDR_ALPHA     = 0.10                # co-expressolog significance threshold
N_NULL        = 1000                # number of rewired replicates
SWAP_FACTOR   = 10                  # double-edge swaps = SWAP_FACTOR * n_edges
RANDOM_SEED   = 1
OUT_PREFIX    = "conservation_null"

USE_EXTERNAL_CALLER = False         # True -> use your own co-expressolog pipeline
CALLER_CMD          = None          # e.g. "Rscript complex_pipeline.R {netdir} {ortho}"
# --------------------------------------------------------------------

rng = random.Random(RANDOM_SEED)
np.random.seed(RANDOM_SEED)


def load_networks(netdir: str) -> dict[str, nx.Graph]:
    nets = {}
    for path in sorted(glob.glob(os.path.join(netdir, "*.tsv"))):
        sp = os.path.splitext(os.path.basename(path))[0]
        g = nx.Graph()
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                a, b = line.split("\t")[:2]
                if a != b:
                    g.add_edge(a, b)
        nets[sp] = g
        print(f"  {sp}: {g.number_of_nodes()} genes, {g.number_of_edges()} edges")
    return nets


def load_orthogroups(path: str):
    df = pd.read_csv(path, sep="\t", names=["og", "species", "gene"], header=0)
    gene2og = {(r.species, r.gene): r.og for r in df.itertuples()}
    # og -> {species: set(genes)}
    og2sp = defaultdict(lambda: defaultdict(set))
    for r in df.itertuples():
        og2sp[r.og][r.species].add(r.gene)
    return gene2og, og2sp


def neighbour_ogs(g: nx.Graph, species: str, gene2og: dict) -> dict[str, set]:
    """Map each gene's network neighbourhood to the set of orthogroups it touches."""
    out = {}
    for node in g.nodes():
        ogs = set()
        for nb in g.neighbors(node):
            og = gene2og.get((species, nb))
            if og is not None:
                ogs.add(og)
        out[node] = ogs
    return out


def coexpressologs_for_pair(gX, spX, gY, spY, gene2og, og2sp):
    """
    Bidirectional hypergeometric neighbourhood-overlap test (ComPlEx logic).
    Returns the set of orthogroups that are co-expressologs between species X and Y
    at FDR < FDR_ALPHA.
    Universe = orthogroups expressed (present as a node mapping) in BOTH species.
    """
    nbX = neighbour_ogs(gX, spX, gene2og)
    nbY = neighbour_ogs(gY, spY, gene2og)
    universe = {og for og, sp in og2sp.items() if spX in sp and spY in sp}
    M = len(universe)
    if M == 0:
        return set()

    pvals, og_keys = [], []
    # candidate orthogroups present in both species
    for og in universe:
        # pick the representative gene per species (first; copy-number handled upstream)
        genesX = [g for g in og2sp[og][spX] if g in gX]
        genesY = [g for g in og2sp[og][spY] if g in gY]
        if not genesX or not genesY:
            continue
        # best (most significant) over gene copies, mirroring "orthogroup as unit"
        best_p = 1.0
        for a in genesX:
            NX = nbX.get(a, set()) & universe
            for b in genesY:
                NY = nbY.get(b, set()) & universe
                k = len(NX & NY)
                if k == 0:
                    continue
                # hypergeometric: overlap of two neighbourhoods drawn from M orthogroups
                pX = hypergeom.sf(k - 1, M, len(NX), len(NY))
                # bidirectional = the same test is symmetric here; keep max p for
                # the two marginal formulations to be conservative
                best_p = min(best_p, pX)
        pvals.append(best_p)
        og_keys.append(og)

    if not pvals:
        return set()
    rej, _, _, _ = multipletests(pvals, alpha=FDR_ALPHA, method="fdr_bh")
    return {og for og, r in zip(og_keys, rej) if r}


def all_pairwise_core(nets, gene2og, og2sp) -> int:
    species = sorted(nets)
    pair_sets = {}
    for spX, spY in itertools.combinations(species, 2):
        s = coexpressologs_for_pair(nets[spX], spX, nets[spY], spY, gene2og, og2sp)
        pair_sets[(spX, spY)] = s
    core = set.intersection(*pair_sets.values()) if pair_sets else set()
    return len(core), {k: len(v) for k, v in pair_sets.items()}


def rewire(g: nx.Graph) -> nx.Graph:
    h = g.copy()
    n_swaps = SWAP_FACTOR * h.number_of_edges()
    try:
        nx.double_edge_swap(h, nswap=n_swaps, max_tries=n_swaps * 20, seed=RANDOM_SEED)
    except nx.NetworkXAlgorithmError:
        pass  # sparse/limited graphs: keep whatever swaps succeeded
    return h


def main():
    print("Loading networks...")
    nets = load_networks(NETWORK_DIR)
    print("Loading orthogroups...")
    gene2og, og2sp = load_orthogroups(ORTHO_FILE)

    print("\nObserved all-pairwise core:")
    obs_core, obs_pairs = all_pairwise_core(nets, gene2og, og2sp)
    for k, v in obs_pairs.items():
        print(f"  {k[0]} vs {k[1]}: {v} co-expressologs")
    print(f"  >>> OBSERVED all-pairwise core = {obs_core} orthogroups")
    print("  (sanity-check this against your reported 118 before trusting the null)\n")

    print(f"Building null ({N_NULL} degree-preserving rewirings)...")
    null = np.empty(N_NULL, dtype=int)
    for i in range(N_NULL):
        rnets = {sp: rewire(g) for sp, g in nets.items()}
        null[i], _ = all_pairwise_core(rnets, gene2og, og2sp)
        if (i + 1) % 50 == 0:
            print(f"  {i+1}/{N_NULL} done (running mean={null[:i+1].mean():.2f})")

    # empirical one-sided p (observed >= null), add-one correction
    p_emp = (np.sum(null >= obs_core) + 1) / (N_NULL + 1)
    mu, sd = null.mean(), null.std(ddof=1)
    z = (obs_core - mu) / sd if sd > 0 else float("inf")
    fold = obs_core / mu if mu > 0 else float("inf")

    print("\n================ RESULT ================")
    print(f"Observed core           : {obs_core}")
    print(f"Null mean +/- sd        : {mu:.2f} +/- {sd:.2f}")
    print(f"Fold-enrichment         : {fold:.1f}x")
    print(f"Empirical one-sided p   : {p_emp:.4g}  (n={N_NULL})")
    print(f"z-score                 : {z:.1f}")
    print("========================================")

    pd.DataFrame({"null_core_size": null}).to_csv(f"{OUT_PREFIX}_null.csv", index=False)
    plt.figure(figsize=(6, 4))
    plt.hist(null, bins=30, color="#9ecae1", edgecolor="white")
    plt.axvline(obs_core, color="#d62728", lw=2, label=f"observed = {obs_core}")
    plt.xlabel("All-pairwise conserved core size (rewired null)")
    plt.ylabel("Replicates")
    plt.title(f"Degree-preserving null  (p={p_emp:.3g}, {fold:.0f}x)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_PREFIX}_hist.png", dpi=150)
    print(f"\nWrote {OUT_PREFIX}_null.csv and {OUT_PREFIX}_hist.png")


if __name__ == "__main__":
    main()
